mydata<-read.table("household_power_consumption.txt",header=TRUE,quote="",sep=";",dec=".",stringsAsFactors = FALSE)
step1<-subset(mydata,as.Date(Date,"%d/%m/%Y")=="2007-02-02" | as.Date(Date,"%d/%m/%Y")=="2007-02-01")
step1$Time<-strftime(strptime(step1$Time,"%R"),"%H:%M")
step1$Time<-str_replace(step1$Time,":",".")
step2<-data.frame(cbind(step1$Time,step1$Global_active_power))
names(step2)<-c("readingTime","activePower")
step2$readingTime<-as.numeric(as.character(step2$readingTime))
step2$activePower<-as.numeric(as.character(step2$activePower))
step3<-step2[order(step2$readingTime),]
par(mar=c(4,4,2,1))
plot(step3$readingTime,step3$activePower,ylab="Global Active Power (kilowatts)","n",xlab="",xaxt="n")
lines(step3$readingTime,step3$activePower)
axis(1,at=seq(0,24,by=12),las=0,labels=c("Thu","Fri","Sat"))
dev.copy(png,file="plot2.png",width=480,height=480)
dev.off()
  