mydata<-read.table("household_power_consumption.txt",header=TRUE,quote="",sep=";",dec=".",stringsAsFactors = FALSE)
step1<-subset(mydata,as.Date(Date,"%d/%m/%Y")=="2007-02-02" | as.Date(Date,"%d/%m/%Y")=="2007-02-01")
step1$Time<-strftime(strptime(step1$Time,"%R"),"%H:%M")
step1$Time<-str_replace(step1$Time,":",".")
plot1<-data.frame(cbind(step1$Time,step1$Global_active_power))
names(plot1)<-c("readingTime","activePower")
plot1$readingTime<-as.numeric(as.character(plot1$readingTime))
plot1$activePower<-as.numeric(as.character(plot1$activePower))
plot1a<-plot1[order(plot1$readingTime),]
plot2<-data.frame(cbind(step1$Time,step1$Voltage))
names(plot2)<-c("readingTime","voltage")
plot2$readingTime<-as.numeric(as.character(plot2$readingTime))
plot2$voltage<-as.numeric(as.character(plot2$voltage))
plot2a<-plot2[order(plot2$readingTime),]
plot3<-data.frame(cbind(step1$Time,step1$Sub_metering_1,step1$Sub_metering_2,step1$Sub_metering_3))
names(plot3)<-c("readingTime","metering1","metering2","metering3")
plot3$readingTime<-as.numeric(as.character(plot3$readingTime))
plot3$metering1<-as.numeric(as.character(plot3$metering1))
plot3$metering2<-as.numeric(as.character(plot3$metering2))
plot3$metering3<-as.numeric(as.character(plot3$metering3))
plot3a<-plot3[order(plot3$readingTime),]
plot4<-data.frame(cbind(step1$Time,step1$Global_reactive_power))
names(plot4)<-c("readingTime","reactivePower")
plot4$readingTime<-as.numeric(as.character(plot4$readingTime))
plot4$reactivePower<-as.numeric(as.character(plot4$reactivePower))
plot4a<-plot4[order(plot4$readingTime),]
par(mfrow=c(2,2),mar=c(4,4,2,1))
plot(plot1$readingTime,plot1$activePower,ylab="Global Active Power","n",xlab="",xaxt="n")
lines(plot1$readingTime,plot1$activePower)
axis(1,at=seq(0,24,by=12),las=0,labels=c("Thu","Fri","Sat"))
plot(plot2$readingTime,plot2$voltage,ylab="Voltage","n",xlab="datetime",xaxt="n")
lines(plot2$readingTime,plot2$voltage)
axis(1,at=seq(0,24,by=12),las=0,labels=c("Thu","Fri","Sat"))
plot(plot3$readingTime,plot3$metering1,ylab="Energy sub metering",xlab="","n",xaxt="n")
axis(1,at=seq(0,24,by=12),las=0,labels=c("Thu","Fri","Sat"))
axis(2,at=seq(0,40,by=10))
lines(step3$readingTime,step3$metering1,col="black")
lines(step3$readingTime,step3$metering2,col="red")
lines(step3$readingTime,step3$metering3,col="blue")
legend("topright",lty=1,bty="n",cex=0.7,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(plot4$readingTime,plot4$reactivePower,ylab="Global_reactive_power","n",xlab="datetime",xaxt="n")
lines(plot4$readingTime,plot4$reactivePower)
axis(1,at=seq(0,24,by=12),las=0,labels=c("Thu","Fri","Sat"))
axis(2,at=seq(0,0.5,by=0.1))
dev.copy(png,file="plot4.png",width=480,height=480)
dev.off()
