mydata<-read.table("household_power_consumption.txt",header=TRUE,quote="",sep=";",dec=".",stringsAsFactors = FALSE)
step1<-subset(mydata,as.Date(Date,"%d/%m/%Y")=="2007-02-02" | as.Date(Date,"%d/%m/%Y")=="2007-02-01")
step1$Time<-strftime(strptime(step1$Time,"%R"),"%H:%M")
step1$Time<-str_replace(step1$Time,":",".")
step2<-data.frame(cbind(step1$Time,step1$Sub_metering_1,step1$Sub_metering_2,step1$Sub_metering_3))
names(step2)<-c("readingTime","metering1","metering2","metering3")
step2$readingTime<-as.numeric(as.character(step2$readingTime))
step2$metering1<-as.numeric(as.character(step2$metering1))
step2$metering2<-as.numeric(as.character(step2$metering2))
step2$metering3<-as.numeric(as.character(step2$metering3))
step3<-step2[order(step2$readingTime),]
par(mfrow=c(1,1),mar=c(4,4,2,1))
plot(step3$readingTime,step3$metering1,ylab="Energy sub metering",xlab="","n",xaxt="n")
axis(1,at=seq(0,24,by=12),las=0,labels=c("Thu","Fri","Sat"))
axis(2,at=seq(0,40,by=10))
lines(step3$readingTime,step3$metering1,col="black")
lines(step3$readingTime,step3$metering2,col="red")
lines(step3$readingTime,step3$metering3,col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png",width=480,height=480)
dev.off()
  